### PR TITLE
fix regarding version matching

### PR DESCRIPTION
**Pull request by elkram**
Ensuring we have the full version string from the matched patch def version list entry.
Example:
Zoom Client for Meetings has versions listed like so :: 5.3.1 (####.####)
We match the 5.3.1 and need to rest of the string to make the package data for the patch version list entry.
We capture the value after matching it, and use that value instead of the self.pkg.version, which is only a portion of the string.

### CODE REVIEW

**Comment by Honestpuck** [comment]
Excellent PR David, it does remove one class of problem version numbers

**Comment by elkram** [comment]
I found a 3rd line that needed adjusting.  Looks like that push made it to this PR.

**Comment by Honestpuck** [comment]
Yeah, it came through as I was checking the first change one last time. Good catch.

**Comment by Honestpuck** [comment]
It still doesn't fix my problem with Android Studio but it has _horrible_ versioning. I've resigned myself to doing it by hand.

**Comment by elkram** [comment]
I realized I didn't see the same self.pkg.version bits in the Production.py handler.  Almost done updating and testing.  Apologies, a looming (unrelated) deadline was rushing my hand.

**Pull request merged**
